In [40]:
from scipy import stats
import numpy as np
age=np.array([24,35,46,51,65])
print(age)
print(age.ndim)   #shows the which dimention of data it is

[24 35 46 51 65]
1


In [22]:
data=np.array([[12,14,15,19],[21,25,28,27],[32,36,31,38],[45,42,41,48]])
print(type(data))
print(data.ndim)
print(data)

<class 'numpy.ndarray'>
2
[[12 14 15 19]
 [21 25 28 27]
 [32 36 31 38]
 [45 42 41 48]]


In [41]:
#Slicing
print(data[0:4,0:3])
print(data[:,0:2])
print(data[0:4:2,0:3:2])

[[12 14 15]
 [21 25 28]
 [32 36 31]
 [45 42 41]]
[[12 14]
 [21 25]
 [32 36]
 [45 42]]
[[12 15]
 [32 31]]


In [44]:
#calculations
print("Minimum value",data.min())
print("Max value",data.max())
print("Mean value",data.mean())
print("Standard deviation",data.std())
print("Variance",data.var())

#Calculation of particular rows and columns
print(data)
print(np.mean(data[1:2,1:3]))
print(np.median(data[0:3,0:2]))
print(stats.mode(data[0:4,0:3],keepdims=True))
data.shape

Minimum value 12
Max value 48
Mean value 29.625
Standard deviation 11.072911767010519
Variance 122.609375
[[12 14 15 19]
 [21 25 28 27]
 [32 36 31 38]
 [45 42 41 48]]
26.5
23.0
ModeResult(mode=array([[12, 14, 15]]), count=array([[1, 1, 1]]))


(4, 4)

In [46]:
#random value creation of data set
#1D array

x1=np.random.randint(10,20,size=50)
x1

array([17, 18, 10, 17, 14, 13, 15, 11, 15, 15, 11, 15, 14, 16, 16, 13, 10,
       10, 18, 15, 16, 12, 16, 18, 10, 17, 15, 15, 11, 12, 15, 10, 19, 19,
       19, 18, 15, 17, 14, 18, 14, 13, 11, 11, 12, 15, 13, 15, 13, 10],
      dtype=int32)

In [49]:
#2D array
x2=np.random.randint(50,100,size=(5,3))
x2

array([[90, 92, 69],
       [98, 96, 75],
       [80, 55, 80],
       [56, 67, 56],
       [69, 85, 59]], dtype=int32)

In [60]:
#3D array
x3=np.random.randint(10,50,size=(3,8,7))
x3

array([[[23, 18, 23, 39, 37, 23, 19],
        [47, 11, 41, 32, 40, 35, 41],
        [49, 47, 28, 31, 47, 10, 45],
        [42, 22, 15, 12, 23, 35, 14],
        [46, 36, 25, 22, 42, 40, 28],
        [48, 27, 41, 30, 44, 43, 41],
        [28, 31, 21, 36, 29, 33, 31],
        [40, 14, 48, 25, 26, 42, 35]],

       [[31, 27, 41, 27, 36, 36, 14],
        [12, 38, 47, 37, 37, 34, 32],
        [30, 28, 47, 49, 32, 33, 40],
        [28, 22, 41, 19, 47, 48, 29],
        [16, 11, 12, 12, 49, 47, 47],
        [18, 35, 39, 11, 24, 26, 35],
        [34, 14, 36, 41, 11, 34, 43],
        [38, 45, 24, 37, 48, 15, 14]],

       [[18, 27, 27, 44, 32, 49, 12],
        [37, 10, 24, 44, 43, 23, 37],
        [36, 45, 16, 26, 38, 11, 47],
        [37, 31, 38, 39, 38, 36, 40],
        [13, 48, 35, 22, 22, 23, 41],
        [35, 17, 39, 32, 10, 26, 47],
        [12, 25, 46, 10, 37, 40, 28],
        [43, 38, 39, 18, 26, 26, 24]]], dtype=int32)

In [69]:
#performing arthematic operations
l=[4,9,5,7,8,9,6,4,1,23,71,1,82,62,35,14]
l2=np.array(l)
l3=l2+1
l4=l2-1
l5=l2*2
l6=l2/2
print("Add",l3)
print("Sub",l4)
print("Mul",l5)
print("Div",l6)

Add [ 5 10  6  8  9 10  7  5  2 24 72  2 83 63 36 15]
Sub [ 3  8  4  6  7  8  5  3  0 22 70  0 81 61 34 13]
Mul [  8  18  10  14  16  18  12   8   2  46 142   2 164 124  70  28]
Div [ 2.   4.5  2.5  3.5  4.   4.5  3.   2.   0.5 11.5 35.5  0.5 41.  31.
 17.5  7. ]
